-- 코드를 입력하세요
SELECT CART_ID
FROM (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME IN ('Yogurt')
    UNION
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME IN ('Milk')
) AS H
GROUP BY CART_ID
HAVING COUNT(NAME) > 1
ORDER BY CART_ID