-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY,' ', U.STREET_ADDRESS1,' ', U.STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTR(U.TLNO,1,3),'-',SUBSTR(U.TLNO,4,4),'-',SUBSTR(U.TLNO,8,4)) AS '전화번호'
FROM USED_GOODS_USER AS U
WHERE (U.USER_ID, U.NICKNAME) IN (
    SELECT U.USER_ID, U.NICKNAME
    FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
    GROUP BY B.WRITER_ID
    HAVING COUNT(B.WRITER_ID) > 2
)
ORDER BY U.USER_ID DESC;


