-- 코드를 입력하세요
SELECT DISTINCT CC.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH 
ON CC.CAR_ID = RH.CAR_ID
WHERE CC.CAR_TYPE LIKE "세단" AND MONTH(START_DATE) = 10
ORDER BY CC.CAR_ID DESC;