-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
    (CASE
        WHEN STATUS = 'RESERVED' THEN '예약중'
        WHEN STATUS = 'SALE' THEN '판매중'
        ELSE '거래완료'
    END) AS STATUS    
FROM USED_GOODS_BOARD
WHERE YEAR(CREATED_DATE) = '2022' AND MONTH(CREATED_DATE) = '10' AND DAY(CREATED_DATE) = '5'
ORDER BY BOARD_ID DESC;