# -- 코드를 입력하세요
# -- 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로 조회
# SELECT CONCAT('home/grep/src/',F.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
# FROM USED_GOODS_FILE F JOIN (
#     SELECT BOARD_ID, MAX(VIEWS)
#     FROM USED_GOODS_BOARD
# ) B ON F.BOARD_ID = B.BOARD_ID
# ORDER BY F.FILE_ID;

SELECT
    CONCAT('/home/grep/src/', FILE.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS FILE
LEFT JOIN USED_GOODS_BOARD AS BOARD
ON FILE.BOARD_ID = BOARD.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC