-- 코드를 작성해주세요
# SELECT COUNT(ID) 'FISH_COUNT', MAX(LENGTH) 'MAX_LENGTH', FISH_TYPE
# FROM (SELECT ID, FISH_TYPE, IFNULL(LENGTH, 10)
#         FROM FISH_INFO) AS FISH_INFO
# WHERE
# GROUP BY 
        
# ORDER BY FISH_TYPE

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH,10)) >= 33
ORDER BY FISH_TYPE